name: Deploy Prd Lambda Laravel Function
on: [workflow_dispatch]
concurrency:
  group: deploy-prd-app
  cancel-in-progress: true
jobs:
  deploy-prd-app:
    runs-on: ubuntu-latest
    env:
      APP_NAME: lambda-laravel-sample
      APP_ENV: prd
      APP_KEY: base64:kowwvxjpdVIxO4y6vlr6RTzZnCVK1S8VgGOkiFPb7B8=
      APP_DEBUG: 'false'
      APP_URL: 'http://localhost'
      LOG_CHANNEL: stack
      LOG_DEPRECATIONS_CHANNEL: 'null'
      LOG_LEVEL: info
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: ''
      BROADCAST_DRIVER: log
      CACHE_DRIVER: file
      FILESYSTEM_DISK: local
      QUEUE_CONNECTION: sync
      SESSION_DRIVER: file
      SESSION_LIFETIME: 120
      MEMCACHED_HOST: 127.0.0.1
      REDIS_HOST: 127.0.0.1
      REDIS_PASSWORD: 'null'
      REDIS_PORT: 6479
      MAIL_MAILER: smtp
      MAIL_HOST: mailpit
      MAIL_PORT: 1025
      MAIL_USERNAME: 'null'
      MAIL_PASSWORD: 'null'
      MAIL_ENCRYPTION: 'null'
      MAIL_FROM_ADDRESS: 'hello@example.com'
      MAIL_FROM_NAME: 'HelloWorld'
      AWS_DEFAULT_REGION: ap-northeast-1
      AWS_BUCKET: ''
      AWS_USE_PATH_STYLE_ENDPOINT: 'false'
      PUSHER_APP_ID: ''
      PUSHER_APP_KEY: ''
      PUSHER_APP_SECRET: ''
      PUSHER_HOST: ''
      PUSHER_PORT: 443
      PUSHER_SCHEME: https
      PUSHER_APP_CLUSTER: ''
      VITE_PUSHER_APP_KEY: ''
      VITE_PUSHER_HOST: ''
      VITE_PUSHER_PORT: ''
      VITE_PUSHER_SCHEME: ''
      VITE_PUSHER_APP_CLUSTER: ''
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{secrets.ROLE_ARN}}
          aws-region: ${{env.AWS_DEFAULT_REGION}}
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Setup Serverless
        run: npm install -g serverless
      - name: Install NodeJS dependencies
        run: npm install
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
      - name: Install PHP dependencies
        run: composer install
      - name: Migrate Database
        run: php artisan migrate
      - name: Severless Deploy
        run: serverless deploy --stage=${{env.APP_ENV}}
