name: CI-PRD
on: 
  workflow_dispatch: null
concurrency:
  group: ci-prd
  cancel-in-progress: true
env:
  REGISTRY: ghcr.io
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  SERVER_PORT: 22
  SERVER_USER: ubuntu
  SERVER_SSH_KEY: ${{secrets.SERVER_SSH_KEY}}
  QUEUE_COUNT: 1
  APP_ENV: prd
  APP_PORT: 5000
  DOCKER_COMMON_ENVS: |- 
    -v /data/prd-charing-storage/app:/var/www/html/storage/app \
    -v /data/prd-charing-storage/logs:/var/www/html/storage/logs \
    -e APP_NAME=Charing \
    -e APP_KEY=${{secrets.APP_KEY_PRD}} \
    -e APP_DEBUG=true \
    -e APP_URL=https://charing.biz/ \
    -e LOG_CHANNEL=stack \
    -e LOG_DEPRECATIONS_CHANNEL=null \
    -e LOG_LEVEL=debug \
    -e DB_CONNECTION=mysql \
    -e DB_HOST=${{secrets.DB_HOST}} \
    -e DB_PORT=${{secrets.DB_PORT}} \
    -e DB_DATABASE=charing_prd \
    -e DB_USERNAME=${{secrets.DB_USERNAME}} \
    -e DB_PASSWORD=${{secrets.DB_PASSWORD}} \
    -e BROADCAST_DRIVER=log \
    -e CACHE_DRIVER=file \
    -e FILESYSTEM_DISK=local \
    -e QUEUE_CONNECTION=database \
    -e QUEUE_FAILED_DRIVER=null \
    -e SESSION_DRIVER=file \
    -e SESSION_LIFETIME=120 \
    -e MEMCACHED_HOST=127.0.0.1 \
    -e REDIS_HOST=127.0.0.1 \
    -e REDIS_PASSWORD=null \
    -e REDIS_PORT=6479 \
    -e MAIL_MAILER=smtp \
    -e MAIL_HOST=mail2.conoha.ne.jp \
    -e MAIL_PORT=587 \
    -e MAIL_USERNAME=noreply@charing.biz \
    -e MAIL_PASSWORD=${{secrets.MAIL_PASSWORD}} \
    -e MAIL_ENCRYPTION=tls \
    -e MAIL_FROM_ADDRESS=noreply@charing.biz \
    -e MAIL_FROM_NAME=Charing \
    -e AWS_DEFAULT_REGION=ap-northeast-1 \
    -e AWS_BUCKET="" \
    -e AWS_USE_PATH_STYLE_ENDPOINT=false \
    -e PUSHER_APP_ID="" \
    -e PUSHER_APP_KEY="" \
    -e PUSHER_APP_SECRET="" \
    -e PUSHER_HOST="" \
    -e PUSHER_PORT=443 \
    -e PUSHER_SCHEME=https \
    -e PUSHER_APP_CLUSTER="" \
    -e VITE_PUSHER_APP_KEY="" \
    -e VITE_PUSHER_HOST="" \
    -e VITE_PUSHER_PORT="" \
    -e VITE_PUSHER_SCHEME="" \
    -e VITE_PUSHER_APP_CLUSTER="" \
    -e PAGE_MAX_LIMIT=50 \
    -e IAM_ARN=${{secrets.IAM_ARN_PRD}} \
    -e IAM_ACCESS_KEY=${{secrets.IAM_ACCESS_KEY_PRD}} \
    -e IAM_SECRECT_KEY=${{secrets.IAM_SECRECT_KEY_PRD}} \
    -e AMAZON_JP_APPLICATION_ID=${{secrets.AMAZON_JP_APPLICATION_ID_PRD}} \
    -e AMAZON_JP_CLIENT_ID=${{secrets.AMAZON_JP_CLIENT_ID_PRD}} \
    -e AMAZON_JP_CLIENT_SECRET=${{secrets.AMAZON_JP_CLIENT_SECRET_PRD}} \
    -e AMAZON_US_APPLICATION_ID=${{secrets.AMAZON_US_APPLICATION_ID_PRD}} \
    -e AMAZON_US_CLIENT_ID=${{secrets.AMAZON_US_CLIENT_ID_PRD}} \
    -e AMAZON_US_CLIENT_SECRET=${{ secrets.AMAZON_US_CLIENT_SECRET_PRD}} \
    -e AMAZON_API_SLEEP_BEFORE_GET_PRODUCT_PRICING=1.0
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/aispel/charing/${{ env.APP_ENV }}-charing:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  deploy-web:
    runs-on: ubuntu-latest
    needs:
      - build-docker-image
    concurrency: deploy-app
    env:
      SERVER_HOST: 35.73.227.145
    steps:
      - name: Pull Docker Image
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          port: ${{ env.SERVER_PORT }}
          script: |-
            export CR_PAT=${{ secrets.GITHUB_TOKEN }}
            echo $CR_PAT | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
            sudo docker pull ghcr.io/aispel/charing/${{ env.APP_ENV }}-charing:latest
            sudo docker logout ghcr.io
      - name: Run Web Docker
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          port: ${{ env.SERVER_PORT }}
          script: |-
            sudo docker stop $(sudo docker ps -a -q --filter="name=${{ env.APP_ENV }}-")
            sudo docker rm $(sudo docker ps -a -q --filter="name=${{ env.APP_ENV }}-")

            if ! [ -d /data/${{ env.APP_ENV }}-charing-storage/ ]; then mkdir /data/${{ env.APP_ENV }}-charing-storage/; fi

            sudo docker run \
              -p ${{ env.APP_PORT }}:8000 \
              -d --name ${{ env.APP_ENV }}-charing-web \
              --restart=always \
              -e APP_ENV=${{ env.APP_ENV }} \
              ${{ env.DOCKER_COMMON_ENVS }} \
              ghcr.io/aispel/charing/${{ env.APP_ENV }}-charing:latest \
              php artisan serve --host=0.0.0.0 --port=8000
      - name: Database Migration
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          port: ${{ env.SERVER_PORT }}
          script: |
            sudo docker exec $(sudo docker ps -a -q --filter="name=${{ env.APP_ENV }}-charing-web") php artisan migrate
      - name: Remove Untagged Images
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SERVER_SSH_KEY }}
          port: ${{ env.SERVER_PORT }}
          script: |
            if [[ $(sudo docker images -f "dangling=true" -q) ]]; then
              sudo docker rmi $(sudo docker images -f "dangling=true" -q)
            fi
  deploy-worker-001-003:
    runs-on: ubuntu-latest
    needs:
      - deploy-web
    concurrency: deploy-worker
    env:
      SERVER_HOST: 35.78.219.203
    steps:
    - name: Pull Docker Image
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USER }}
        key: ${{ env.SERVER_SSH_KEY }}
        port: ${{ env.SERVER_PORT }}
        script: |-
          export CR_PAT=${{ secrets.GITHUB_TOKEN }}
          echo $CR_PAT | sudo docker login ghcr.io -u ${{ github.actor }} --password-stdin
          sudo docker pull ghcr.io/aispel/charing/${{ env.APP_ENV }}-charing:latest
          sudo docker logout ghcr.io
    - name: Run Queue Dockers
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USER }}
        key: ${{ env.SERVER_SSH_KEY }}
        port: ${{ env.SERVER_PORT }}
        script: |
          sudo docker stop $(sudo docker ps -a -q --filter="name=${{ env.APP_ENV }}-")
          sudo docker rm $(sudo docker ps -a -q --filter="name=${{ env.APP_ENV }}-")

          for i in $(seq -f "%03g" 1 3)
          do
            sudo docker run \
              -d --name ${{ env.APP_ENV }}-charing-worker-$i \
              --restart=always \
              -e APP_ENV=${{ env.APP_ENV }} \
              ${{ env.DOCKER_COMMON_ENVS }} \
              ghcr.io/aispel/charing/${{ env.APP_ENV }}-charing:latest \
              php artisan queue:work --queue=update_amazon_jp_exhibit,update_yahoo_jp_exhibit,exhibit_to_amazon_jp,exhibit_to_yahoo_jp,extract_amazon_info_for_exhibit,update_amazon_info,extract_amazon_info
          done
          for i in $(seq -f "%03g" 101 103)
          do
            sudo docker run \
              -d --name ${{ env.APP_ENV }}-charing-worker-$i \
              --restart=always \
              -e APP_ENV=${{ env.APP_ENV }} \
              ${{ env.DOCKER_COMMON_ENVS }} \
              ghcr.io/aispel/charing/${{ env.APP_ENV }}-charing:latest \
              php artisan queue:work --queue=download_amazon_jp_product_images
          done
    - name: Remove Untagged Images
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ env.SERVER_HOST }}
        username: ${{ env.SERVER_USER }}
        key: ${{ env.SERVER_SSH_KEY }}
        port: ${{ env.SERVER_PORT }}
        script: |
          if [[ $(sudo docker images -f "dangling=true" -q) ]]; then
            sudo docker rmi $(sudo docker images -f "dangling=true" -q)
          fi
